import secrets
import datetime
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.database import get_db
from app.auth import get_current_user
from app.models.api_key import ApiKey

router = APIRouter()

class ApiKeyCreate(BaseModel):
    name: Optional[str] = "Gmail Extension"

@router.post("/api-keys", status_code=status.HTTP_201_CREATED)
def create_api_key(
    body: ApiKeyCreate,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user)
):
    """
    Generates a new random API key tied to the currently logged in user's account.
    """
    # Generate cryptographically secure prefix-tagged key token
    random_token = secrets.token_urlsafe(32)
    generated_key = f"et_live_{random_token}"

    new_key = ApiKey(
        user_id=current_user_id,
        key=generated_key,
        name=body.name or "Gmail Extension",
        created_at=datetime.datetime.utcnow()
    )

    db.add(new_key)
    db.commit()
    db.refresh(new_key)

    return {
        "status": "success",
        "api_key": {
            "id": new_key.id,
            "name": new_key.name,
            "key": new_key.key,
            "created_at": new_key.created_at
        }
    }

@router.get("/api-keys")
def list_api_keys(
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user)
):
    """
    Lists all active API keys generated by the currently authenticated user.
    """
    keys = (
        db.query(ApiKey)
        .filter(ApiKey.user_id == current_user_id)
        .order_by(ApiKey.created_at.desc())
        .all()
    )

    return [
        {
            "id": key.id,
            "name": key.name,
            "key": key.key,
            "created_at": key.created_at
        }
        for key in keys
    ]

@router.delete("/api-keys/{key_id}", status_code=status.HTTP_200_OK)
def delete_api_key(
    key_id: int,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user)
):
    """
    Revokes and deletes an API key belonging to the currently authenticated user.
    """
    key_record = (
        db.query(ApiKey)
        .filter(ApiKey.id == key_id, ApiKey.user_id == current_user_id)
        .first()
    )

    if not key_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="API Key not found or does not belong to your account."
        )

    db.delete(key_record)
    db.commit()

    return {"status": "success", "message": "API key revoked successfully."}
